import {
  Sparkles,
  Zap,
  Megaphone,
  Code,
  Palette,
  TrendingUp,
  Bot,
  Share2,
  PenTool,
  Mouse,
  Edit3,
  FileText,
  HeadphonesIcon,
  DollarSign,
  Cog,
  BarChart3,
  Globe,
  Box,
  Smartphone,
  Video,
  Wrench,
  HomeIcon,
  FolderOpen,
  Zap as AutomationIcon,
  Layers,
  Mail,
  Chrome,
  Users,
  Briefcase,
  Activity,
  Coins,
  ShoppingCart,
  Wifi,
  Cpu,
} from "lucide-react";
import { Category } from "@/lib/types";

export const CATEGORIES: Category[] = [
  { name: "All", icon: HomeIcon, href: "/" },
  // Catégories les plus populaires en premier
  { name: "Artificial intelligence", icon: Sparkles, href: "/ai" },
  { name: "Productivity", icon: Zap, href: "/productivity" },
  { name: "Marketing", icon: Megaphone, href: "/marketing" },
  { name: "SEO", icon: TrendingUp, href: "/seo" },
  { name: "Directories", icon: FolderOpen, href: "/directories" },
  { name: "Automation", icon: AutomationIcon, href: "/automation" },
  { name: "Boilerplates", icon: Layers, href: "/boilerplates" },
  { name: "Developer tools", icon: Code, href: "/developer-tools" },
  { name: "Writing", icon: Edit3, href: "/writing" },
  { name: "Design", icon: Palette, href: "/design" },
  { name: "No code", icon: Mouse, href: "/no-code" },
  { name: "Community", icon: Users, href: "/community" },
  { name: "Email marketing", icon: Mail, href: "/email-marketing" },
  { name: "Chrome extensions", icon: Chrome, href: "/chrome-extensions" },
  { name: "Freelancer tools", icon: Briefcase, href: "/freelancer-tools" },
  { name: "Analytics", icon: BarChart3, href: "/analytics" },
  { name: "AI agents", icon: Cpu, href: "/ai-agents" },
  { name: "Social media", icon: Share2, href: "/social-media" },
  { name: "Content creation", icon: PenTool, href: "/content-creation" },
  { name: "Fintech", icon: Coins, href: "/fintech" },
  { name: "E-commerce", icon: ShoppingCart, href: "/ecommerce" },
  { name: "Website builders", icon: Globe, href: "/website-builders" },
  { name: "iOS", icon: Smartphone, href: "/ios" },
  { name: "Video", icon: Video, href: "/video" },
  { name: "Monitoring", icon: Activity, href: "/monitoring" },
  { name: "Remote work", icon: Wifi, href: "/remote-work" },
  { name: "Chatbots", icon: Bot, href: "/chatbots" },
  { name: "Blogging", icon: FileText, href: "/blogging" },
  { name: "Sales", icon: DollarSign, href: "/sales" },
  { name: "Customer support", icon: HeadphonesIcon, href: "/customer-support" },
  { name: "Developer APIs", icon: Box, href: "/developer-apis" },
  { name: "Building products", icon: Wrench, href: "/building-products" },
  { name: "Productized services", icon: Cog, href: "/productized-services" },
];
